name: Build WinDivert

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Download and Unzip WinDivert
        run: |
          Invoke-WebRequest -Uri https://reqrypt.org/download/WinDivert-2.2.2-Source.zip -OutFile WinDivert.zip
          Expand-Archive -Path WinDivert.zip -DestinationPath .
          dir WinDivert-2.2.2
        shell: powershell

      - name: Retarget Visual Studio projects to latest toolset
        run: |
          Get-ChildItem -Recurse -Filter *.vcxproj | ForEach-Object {
            (Get-Content $_.FullName) -replace 'v140', 'v143' | Set-Content $_.FullName
          }
        working-directory: WinDivert-2.2.2
        shell: powershell

      - name: Build WinDivert DLL (Release x64)
        run: |
          msbuild dll\windivert.vcxproj /p:Configuration=Release /p:Platform=x64
        working-directory: WinDivert-2.2.2
        shell: cmd

      - name: Upload WinDivert DLL
        uses: actions/upload-artifact@v4
        with:
          name: WinDivert-DLL
          path: WinDivert-2.2.2\dll\bin\WinDivert.dll
