name: Build WinDivert

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Download and Unzip WinDivert
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://reqrypt.org/download/WinDivert-2.2.2-Source.zip -OutFile WinDivert.zip
          Expand-Archive -Path WinDivert.zip -DestinationPath .
          dir WinDivert-2.2.2

      - name: Add WDK environment to PATH
        run: |
          echo ##[group]List installed WDKs
          dir "C:\Program Files (x86)\Windows Kits\10"
          echo ##[endgroup]
        shell: cmd

      - name: Build with WDDK script
        run: wddk-build.bat
        working-directory: WinDivert-2.2.2
        shell: cmd

      - name: Upload WinDivert DLL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WinDivert-Binaries
          path: WinDivert-2.2.2\dll\bin\
