name: Build WinDivert

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Unzip WinDivert
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://reqrypt.org/download/WinDivert-2.2.2-Source.zip -OutFile WinDivert.zip
          Expand-Archive -Path WinDivert.zip -DestinationPath .
          dir WinDivert-2.2.2

      - name: Install Visual Studio + WDK build tools
        run: |
          choco install visualstudio2022-workload-manageddesktop --yes
          choco install visualstudio2022-workload-nativedesktop --yes
          choco install visualstudio2022-workload-netweb --yes
          choco install visualstudio2022buildtools --yes
          choco install windows-sdk-10-version-2104-all --yes
        shell: powershell

      - name: Verify WDK presence
        run: |
          where build
          where msbuild
        shell: cmd

      - name: Build with wddk-build.bat
        run: |
          call wddk-build.bat
        working-directory: WinDivert-2.2.2
        shell: cmd

      - name: Upload WinDivert binaries
        uses: actions/upload-artifact@v4
        with:
          name: WinDivert-Binaries
          path: WinDivert-2.2.2\dll\bin\
